name: "azure-resource-locks - disable"

# Docs:
# https://aka.ms/yaml
trigger: none
# Don't run against PRs
pr: none
 
parameters:
  - name: subscription
    displayName: Subscription
    type: string
    default: DCD-CNP-DEV
    values:
    - 'DCD-CNP-DEV'
    - 'DCD-CNP-QA'
    - 'DCD-CNP-PROD'
    - 'DTS-SHAREDSERVICES-DEV'
    - 'DTS-SHAREDSERVICES-TEST'
    - 'DTS-SHAREDSERVICES-DEMO'
    - 'DTS-SHAREDSERVICES-STG'
    - 'DTS-SHAREDSERVICES-PROD'
    - 'HMCTS-HUB-PROD-INTSVC'
    - 'HMCTS-HUB-NONPROD-INTSVC'
    - 'DCD-CFTAPPS-PROD'
    - 'Reform-CFT-VH-Dev'
    - 'DCD-CFT-VH-Pilot'
    - 'DTS-HERITAGE-EXTSVC-PROD'
    - 'DTS-HERITAGE-INTSVC-PROD'
    - 'DTS-HERITAGE-EXTSVC-STG'
    - 'DTS-DATAINGEST-PROD'
  - name: resourceGroup
    displayName: Resource group
    type: string

jobs:
  - job: Disable_Resource_locks
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureCLI@2
      displayName: 'Disable resource locks'
      inputs:
        scriptType: bash
        scriptLocation: scriptPath
        # hack to map subscription name to service connection name
        azureSubscription: ${{ parameters.subscription }}
        scriptPath: scripts/disable-resource-locking.sh
      env:
       RESOURCE_GROUPS_LIST: ${{ parameters.resourceGroup }}
